### ISSUE TITLE
Badge name "quality" is a bit too generic

### ISSUE THREAD

**Issue by racodond** [QualInsight/qualinsight-plugins-sonarqube-badges#17]
Badge name "quality" is a bit too generic from my point of view. Could it be renamed into "code quality" or "sonarqube" or "sonarqube code quality"? Could it make sense to make it configurable?

**Comment by pawlakm** [comment]
Current badge will be renamed to "quality gate". I don't plan to make it configurable as other badges will be also available.

**Comment by pawlakm** [comment]
committed
