### ISSUE TITLE
No configuration panel

### ISSUE THREAD

**Issue by Talrik** [QualInsight/qualinsight-plugins-sonarqube-badges#49]
Hi, 

I have installed SVG Badges 1.2.1 on Sonarqube 4.5.6 but I don't get the configuration panel. 
It still looks like this: 
![noconfiguration](https://cloud.githubusercontent.com/assets/2892818/19558079/c20423ba-96c8-11e6-8d73-4be52c6fa339.png)

The plugin is working but I would like to enable the measures badges. Is there a fix or perhaps a workaround?

Thanks, 
Phil

**Comment by pawlakm** [comment]
Hi, sorry for the late reply. Measures badges were introduced with version 2.0.0 of the plugin. That's why you can't use them with 1.2.1.

All the best,

Michel
