### ISSUE TITLE
Sonarcloud integration

### ISSUE THREAD

**Issue by Ekryd** [QualInsight/qualinsight-plugins-sonarqube-badges#69]
Hi,

Does your plugin work with Sonarcloud (https://about.sonarcloud.io)?
I have a hard time finding the correct place to install the plugin.

Kind regards,
/Björn

**Comment by proustibat** [comment]
@Ekryd 
I found this page: 
https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/wiki/Quality-Gate-status-badges
I think you could also find what you want here. 

For example:
https://sonarcloud.io/api/badges/gate?key=< project or view key >
